name: security_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # For playing video streams from network (RTSP/HTTP)
  flutter_vlc_player: ^7.4.1

  # For state management (extensively used in future weeks)
  provider: ^6.1.2

  # For making HTTP requests to login/signup APIs (used in Week 2)
  http: ^1.2.1

  # For storing login tokens locally (used in Week 2)
  shared_preferences: ^2.2.3

  # For routing and navigation between screens
  go_router: ^14.1.0

  # Firebase dependencies for push notifications
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.1

  # For beautiful loading spinners
  flutter_spinkit: ^5.2.1

  cupertino_icons: ^1.0.6

  video_player: ^2.5.1

  intl: ^0.19.0

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# Flutter configuration
flutter:
  uses-material-design: true